version: '2.0'

services:
  node:
    image: node:16-alpine
    volumes:
      - .:/data/
    working_dir: /data

  ui:
    build: .
    volumes:
      - .:/data/
    command: npm run serve
    # command: npm run serve:prod
    ports:
      - '8000:8000'
    depends_on:
      - api

  api:
    image: silintl/idp-pw-api:develop
    ports:
      - '8080:80'
    depends_on:
      - profileDb
      - memcache
      - broker
      - zxcvbn
      - idp
    env_file:
      - ./.env.local
    environment:
      MYSQL_HOST: 'profileDb'
      MYSQL_DATABASE: 'profile'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'pass'
      EMAILER_CLASS: \tests\mock\emailer\FakeEmailer
      EMAIL_SERVICE_baseUrl: 'dummy'
      EMAIL_SERVICE_accessToken: 'dummy'
      EMAIL_SERVICE_assertValidIp: 'false'
      ALERTS_EMAIL_ENABLED: 'false'
      HELP_CENTER_URL: 'https://example.org/help-center'
      FROM_NAME: 'Tech support'
      SUPPORT_PHONE: '007-867-5309'
      SUPPORT_EMAIL: 'support@example.org'
      SUPPORT_URL: 'https://www.example.org/support'
      SUPPORT_FEEDBACK: 'https://www.example.org/support-feedback'
      UI_URL: 'https://profile.gtis.guru/#'
      LOGO_URL: 'https://www.sil.org'
      UI_CORS_ORIGIN: 'https://profile.gtis.guru'
      ACCESS_TOKEN_HASH_KEY: 'KEY4TESTING'
      ZXCVBN_API_BASEURL: 'http://zxcvbn:3000'
      ID_BROKER_baseUrl: 'http://broker'
      ID_BROKER_accessToken: 'local-testing-abc123'
      ID_BROKER_assertValidBrokerIp: 'false'
      AUTH_SAML_signRequest: 'false'
      AUTH_SAML_checkResponseSigning: 'false'
      AUTH_SAML_requireEncryptedAssertion: 'false'
      AUTH_SAML_idpCertificate: ''
      AUTH_SAML_spCertificate: ''
      AUTH_SAML_spPrivateKey: ''
      AUTH_SAML_entityId: 'profile-api.gtis.guru'
      AUTH_SAML_ssoUrl: 'http://idp.gtis.guru/saml2/idp/SSOService.php'
      AUTH_SAML_sloUrl: 'http://idp.gtis.guru/saml2/idp/SingleLogoutService.php'
      PASSWORD_RULE_minLength: '10'
      PASSWORD_RULE_maxLength: '255'
      PASSWORD_RULE_minScore: '3'
      MEMCACHE_CONFIG1_host: 'memcache'
    command: [ 'bash', '-c', 'whenavail profileDb 3306 60 ./yii migrate --interactive=0 && ./run.sh' ]

  profileDb:
    image: mariadb:latest
    ports:
      - '3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'r00tp@ss!'
      MYSQL_DATABASE: 'profile'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'pass'

  profilePhpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8081:80'
    depends_on:
      - profileDb
    environment:
      PMA_HOST: 'profileDb'
      PMA_USER: 'user'
      PMA_PASSWORD: 'pass'

  memcache:
    image: memcached:1.4-alpine
    ports:
      - "11211"  

  zxcvbn:
    image: wcjr/zxcvbn-api
    ports:
      - '3000'
  
  proxy:
    # https://github.com/silinternational/traefik-https-proxy
    image: silintl/traefik-https-proxy
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - ui
      - api
    volumes:
      - ./development/cert:/cert
    env_file:
      - ./.env.local
    environment:
      DNS_PROVIDER: 'cloudflare'
      LETS_ENCRYPT_CA: 'staging'
      TLD: 'gtis.guru'
      SANS: 'profile.gtis.guru,profile-api.gtis.guru,idp.gtis.guru'
      FRONTEND1_DOMAIN: 'profile.gtis.guru'
      FRONTEND2_DOMAIN: 'profile-api.gtis.guru'
      FRONTEND3_DOMAIN: 'idp.gtis.guru'
      BACKEND1_URL: 'http://ui:8000'
      BACKEND2_URL: 'http://api:80'
      BACKEND3_URL: 'http://idp:80'

  broker:
    image: silintl/idp-id-broker:develop
    volumes:
      - ./development/m991231_235959_insert_test_users.php:/data/console/migrations/m991231_235959_insert_test_users.php
    ports:
      - '8090:80'
    depends_on:
      - brokerDb
    env_file:
      - ./.env.local
    environment:
      APP_ENV: 'dev'
      API_ACCESS_KEYS: 'local-testing-abc123'
      MIGRATE_PW_FROM_LDAP: 'false'
      MYSQL_HOST: 'brokerDb'
      MYSQL_DATABASE: 'broker'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'pass'
      EMAILER_CLASS: Sil\SilIdBroker\Behat\Context\fakes\FakeEmailer
      EMAIL_SERVICE_baseUrl: 'dummy'
      EMAIL_SERVICE_accessToken: 'dummy'
      EMAIL_SERVICE_assertValidIp: 'false'
      EMAIL_SIGNATURE: 'one red pill, please'
      SUPPORT_EMAIL: 'support@example.org'
      HELP_CENTER_URL: 'https://example.org/help'
      PASSWORD_FORGOT_URL: 'https://example.org/forgot'
      PASSWORD_PROFILE_URL: 'https://example.org/profile'
    command: [ 'bash', '-c', 'whenavail brokerDb 3306 60 ./yii migrate --interactive=0 && ./run.sh' ]

  brokerDb:
    image: mariadb:latest
    ports:
      - '3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'r00tp@ss!'
      MYSQL_DATABASE: 'broker'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'pass'

  brokerPhpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8091:80'
    depends_on:
      - brokerDb
    environment:
      PMA_HOST: 'brokerDb'
      PMA_USER: 'user'
      PMA_PASSWORD: 'pass'

  idp:
    image: silintl/ssp-base:develop
    volumes:
      - ./development/authsources.php:/data/vendor/simplesamlphp/simplesamlphp/config/authsources.php
      - ./development/saml20-idp-hosted.php:/data/vendor/simplesamlphp/simplesamlphp/metadata/saml20-idp-hosted.php
      - ./development/saml20-sp-remote.php:/data/vendor/simplesamlphp/simplesamlphp/metadata/saml20-sp-remote.php
      # - ./development/php-debugging.ini:/etc/php/7.0/apache2/php.ini
      - ./development/default-logo.png:/data/vendor/simplesamlphp/simplesamlphp/www/logo.png
    ports:
      - '8088:80'
    depends_on:
      - silAuthDb
      - broker
    env_file:
      - ./.env.local
    environment:
      ADMIN_PASS: 'a'
      BASE_URL_PATH: 'https://idp.gtis.guru'
      SECURE_COOKIE: 'false'
      SHOW_SAML_ERRORS: 'true'
      ADMIN_PROTECT_INDEX_PAGE: 'false'
      THEME_USE: 'material:material'
      ADMIN_EMAIL: 'admin1@example.org'
      SECRET_SALT: 'NlFalr5Faa73coPUFPP78BCi2ZUYhL+qVCOuJ466Bh4='
      IDP_DOMAIN_NAME: 'idp.gtis.guru'
      MFA_SETUP_URL: 'https://example.org/mfa-setup'
      MFA_LEARN_MORE_URL: '//example.org/learn-more'
      MYSQL_HOST: 'silAuthDb'
      MYSQL_DATABASE: 'silauth'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'pass'
      ID_BROKER_BASE_URI: 'http://broker'
      ID_BROKER_ACCESS_TOKEN: 'local-testing-abc123'
      ID_BROKER_ASSERT_VALID_IP: 'false'
      REMEMBER_ME_SECRET: 'dummy'
      PASSWORD_CHANGE_URL: 'https://profile.gtis.guru/#/password/create'
      PASSWORD_FORGOT_URL: 'https://profile.gtis.guru/#/password/forgot'
      PROFILE_URL: 'https://profile.gtis.guru/#'
    command: [ 'bash', '-c', 'whenavail silAuthDb 3306 60 ./run-idp.sh' ]

  silAuthDb:
    image: mariadb:latest
    ports:
      - '3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'r00tp@ss!'
      MYSQL_DATABASE: 'silauth'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'pass'
