name: deepfactor-scan
on:
  push:
    branches: [ main, develop, feature/deepfactor ]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: public.ecr.aws/deepfactor/df/runtime:3.3.3-2346
      env:
        DF_RUN_TOKEN: ${{ secrets.DF_RUN_TOKEN }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Scan with Deepfactor
      run: dfctl scan --source fs --app ${{ github.event.repository.name }} --config ${{ github.event.repository.name }} --version ${{ github.ref_name }} .
