name: Build

on:
  push:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
    - name: Build
      run: |
          mv .env.dist .env.local
          npm install
          npm run build
